### PR TITLE
Convert pam_mujoco.cpp to UNIX-style line endings

### PR DESCRIPTION
**Pull request by luator**
## Description

pam_mujoco.cpp was the only file in this repo that used Windows-style
line endings ("\r\n"), so convert it to UNIX-style ("\n") to be
consistent with the rest.

## How I Tested

`cat -A pam_mujoco.cpp` prints the file and visualises the line endings (`^M$` for Windows-style, `$` for UNIX-style)

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by luator** [comment]
The diff is unfortunately not very useful, as it just shows that every line changed...

**Review by dtrb — APPROVED** [review]
Thanks for paying attention to details! LGTM.

**Comment by luator** [comment]
I actually only noticed it because it somehow triggered a but in the auto-formatter plugin of my editor :D

**Comment by dtrb** [comment]
:)

**Pull request merged**
